// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zesbaoyralbtdvtjzeda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplc2Jhb3lyYWxidGR2dGp6ZWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTgxNDgsImV4cCI6MjA2OTk5NDE0OH0.587OL7spTLjNIEdVOPaePzlQDRXsrz54hl36klCtaEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);